// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly: AssemblyVersionAttribute("1.2.0")>]
[<assembly: AssemblyFileVersionAttribute("1.2.0")>]
[<assembly: AssemblyInformationalVersionAttribute("1.2.0")>]
do ()

module internal AssemblyVersionInformation =
  [<Literal>]
  let AssemblyVersion = "1.2.0"

  [<Literal>]
  let AssemblyFileVersion = "1.2.0"

  [<Literal>]
  let AssemblyInformationalVersion = "1.2.0"
